-- CreateEnum
CREATE TYPE "CommissionType" AS ENUM ('PERCENTAGE', 'FLAT');

-- AlterTable
ALTER TABLE "Agent" ADD COLUMN     "additionalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "commissionType" "CommissionType" NOT NULL DEFAULT 'PERCENTAGE',
ADD COLUMN     "commissionValue" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "totalEarned" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalPaid" DOUBLE PRECISION NOT NULL DEFAULT 0;
